version: '3.8'

services:
  my-app:
    build:
      context: .
      args:
        STUDENT_NAME: "Leonardo Tyoes Huibu"
        STUDENT_NIM: "00000065503"
    ports:
      - "80:80"  # Map container port 3000 to host port 3000

